### PR TITLE
feat(Rotational teleport): teleport with player reorientation && fix(Simple Pointer)

### PR DESCRIPTION
**Pull request by thacio**
- Added a new teleport system that can reorient the player either to face the pointed direction or a specific object/world point. Added and example scene "036_RotationalTeleport", also uploaded a demonstration video https://www.youtube.com/watch?v=swWv6ODBV48.
- Made changes to VRTK_SimplePointer (especially) and VRTK_WorldPointer to make them more usable in different situations from outer toolkit scripts while correcting bugs and making them more stable.
- Some other minor changes in other scripts for usability.

The toolkit is currently great (a thousand times better than the UE4 side :D ), but one recurring issue (of course, in my opinion) is that it is too self-contained. Functionalities should be more exposed and optional so that developers could choose to manage the toolkit features by himself or use the own toolkit managers. 
For example, the VRTK_WorldPointer subscribes himself (no choice there) to the VRTK_ControllerEvents, and will activate on VRTK_ControllerEvents, so if a dev wants to manage when and how the beams are activate, he will have to dig and change the toolkit code. In this case, I didn't remove this self centering of the pointers as I didn't want to break the toolkit pattern, but made some changes to be manageable by outsid scripts, like exposing (as events) when pointer goes on or off, get the direction pointed, allowing runtime enabling/disabling the pointer script to turn it on or off and fixes to make everything work. For this last one, the outside script still needs to manage internal variables (such as turning on/off showtip and the pointer visibility to Always Off), so the script still needs improvement. One example of this is in the demonstration video, which when the player charges the blast with both hands, the teleport is switched to the headset gaze. When the start charging, my state manager has to set showtip to off, pointer visibility to always off, and just then turn off the script, and turn on the headset pointer.
Just a consideration for future changes, the toolkit is already rocking.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 41576d954ec933172ec5fedacbde320cc6723ec1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 77d3f4f8fc1e55180af5590fb3db1c31e05c07f0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d887b3e0faa4d9df349c5d45e29ddba046783c02
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
Really like the idea in this PR.

Some things need sorting out with the commits, but I'll go through it and provide feedback where necessary so we can get this cleaned up and merged in.

I'll try and go over this tomorrow

**Comment by thacio** [comment]
I'm new to github so I'm I still need to get used to this stuff. The first commit brings all the script and stuff, but the scene weren't opening because I didn't put the meta files. So the others are just updating the scene and meta to fix things, so I didn't write anything.

**Comment by thestonefox** [comment]
@thacio don't worry about it :) i'll help you get it sorted out (even with git fu if required)

If you're not a member of the slack channel then it's definitely worth joining, lots of dev activity in there.

https://vrtk-slack-invite.herokuapp.com/

**Comment by thacio** [comment]
Done. 

I have no idea what I'm doing, lol. I just saw that the first commit was merging from a branch.
Worst case scenario, I'll just e-mail you the script.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 41576d954ec933172ec5fedacbde320cc6723ec1
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: 77d3f4f8fc1e55180af5590fb3db1c31e05c07f0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: d887b3e0faa4d9df349c5d45e29ddba046783c02
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
It may be worth resubmitting a new PR with just your work as one commit.

**Comment by thacio** [comment]
There were some commits today in the pointers, so I might need to adjust the scripts. I'll submit a new commit after I get everything working.

**Comment by thestonefox** [comment]
Superseded with https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/338

**Pull request closed without merging**
