### PR TITLE
feat(CameraRig): Added a script to move the CameraRig

### PR DESCRIPTION
**Pull request by appdevtk**
Only when outside a circle. Aims to create a virtually bigger play area.
I have added a demo scene to test the script.

Just add the VRTK_RoomExtender to the CameraRig and you are ready to go.
If you want to visualize the circle you can add a cylinder to the debug transform.

I saw this kind of movement in a presentation and thought it would be nice to simulate bigger play areas.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bab30df97ddb5939fbf92f9856ba877f52c5c9ea
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 48acfb2e6c80dbd2dc5066d0caab77af198ba746
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
Not sure what's up with it but first the example scene the headset view is upside down (can't see why it is though!)

secondly, I attached the new script in a different example scene (and the headset is fine, so nothing to do with the script). But the script doesn't seem to do anything for me.

The movement variable is always vector3.zero no matter where I move to :/

**Comment by appdevtk** [comment]
I am on unity version 5.4b19 and can't reproduce your errors. Does the script find the eyeCamera and the cameraRig? It should move the debug Transform when you try to step outside of it. In the demo scene i used a cylinder paranted to the cameraRig.

**Comment by thestonefox** [comment]
Ah that may be the issue, unity 5.4 has some changes to it within SteamVR, it relocates the camera eyes and the camera head object.

Take a look at the HeadsetCollisionFade script

**Comment by appdevtk** [comment]
I'll take a look at Unity 5.3 tomorrow, but I have changed the script to manually set the correct transform. In Unity 5.4 it uses the SteamVR_Camera located at the eyes, but if unity 5.3 moves the camera head you can add that transform. Thinking about it... You could also add an arrow to move your playspace :)

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: dd6c490c32865c576eb168d2e588dc06fdecae4d
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
