### PR TITLE
feat(Interaction): add handle snap grab mechanic

### PR DESCRIPTION
**Pull request by drifio**
The new `Handle Snap` grab mechanic allows you to specify a transform as
a child of the VRTK_InteractableObject to which the grab will snap. Any
rotation applied to the handle will rotate the object around the handle.

### CODE REVIEW

**Comment by thestonefox** [comment]
:+1: looks good I'll pull down your version in the morning and give it a once over, if it's all ok I'm happy to merge!

**Comment by thestonefox** [comment]
@drifio 
Would you mind updating the README.md in your commit? (rebase it in so it's only one commit and that would be super! help offered if rebasing is new to you!)

In the `Interactable Object (VRTK_InteractableObject)` section underneath the `Grab Interactions` -> `Grab Snap Type` Just needs a new parameter adding:

```
   * `Handle_Snap` allows for an empty GameObject as a child of the
   interactable object to be used as the reference snap point. On grab,
   this empty GameObject rotation and position is used to orientate
   the grabbed interactable object to the controller.
```

**Comment by thestonefox** [comment]
Sure, so what you want to do is do an interactive rebase to a commit before your commit (this is assuming you're using git command line tools!)

So rough steps would be:

* `git log --oneline -10` - this will get you your last 10 commits (newest first), get the hash code of the commit before your commit (it may be `8f8a729 fix(README): fix faq video links`)
* then you want to do an interactive rebase to the commit point before your commit: `git rebase -i 8f8a729`
* this will bring up a window showing you commits to work with (you'll probably only see 1 commit). You need to change the letter next to your commit (on the left) to `e` (e for edit) then save and close that file (this will now put you into rebase mode on that commit, which means you're basically able to change things within that commit).
* So now just change the `README.md` file to what it needs to be, then `git add README.md` which will add your changes back in ready to be commited
* Now you want to commit your changes to the current commit so you can just do `git commit --amend -C HEAD` which will amend the current commit at the HEAD position (the head will be your current commit as you've gone back in time to that commit).
* Finally you need to continue your rebase to roll up the changes `git rebase --continue`
* Now you'll be back at the head of your repo and you can just force push your changes `git push origin master -f` (-f does the force push).


So that's how to do a rebase!

But.................

If your commit is already the last commit then you don't need to do any of that, you can just do:

* Change the `README.md` file to what it needs to be
* Do `git add README.md` to add that to be commited
* Then amend your last commit with `git commit --amend -C HEAD`
* Finally do a force push with `git push origin master -f`

Your commit and PR will automatically be updated too :)

Let me know if you need any more help or if things go wrong

**Comment by drifio** [comment]
Looks like it worked ok? Confirm for me that I didn't mess anything up ;p

**Comment by thestonefox** [comment]
:+1: looks good :shipit: :heart: :green_heart: :yellow_heart: :blue_heart:

**Pull request merged**
