### PR TITLE
feat(Locomotion): Player Jump

### PR DESCRIPTION
**Pull request by ajaxlex**
Adds the player jump script, and demo scene 039 to exercise it.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 98c8d27f5f4671267320da4790a95d8cf211d60b
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 98c8d27f5f4671267320da4790a95d8cf211d60b
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 6113611ba00388989adc60abb397815c9657db90
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by xEvoGx** [comment]
Any chance this is related to #393 ?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 98c8d27f5f4671267320da4790a95d8cf211d60b
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 6113611ba00388989adc60abb397815c9657db90
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by ajaxlex** [comment]
Yes - it looks like this addresses #393.  I can also see that my local amend is not picking up my new file!!

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 98c8d27f5f4671267320da4790a95d8cf211d60b
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 6113611ba00388989adc60abb397815c9657db90
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by ajaxlex** [comment]
Getting rid of those other commits is a pain.  I can squash and rebase, or cop out and open another branch, or just scrub the whole fork and restart it.  There's really only one file ( plus a copy of the teleport scene ) so not hard to reconstitute.  I am commenting here because I'm not clear about what would happen in your PR interface if I nuke stuff.  The comments are not critical.

**Pull request closed without merging**
