### PR TITLE
chore(examples): move all example scripts to namespace vrtk.example

### PR DESCRIPTION
**Pull request by jcrombez**
Regarding issue https://github.com/thestonefox/SteamVR_Unity_Toolkit/issues/521

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ff4ff3f31d4614a3c60ee5a9fef9f507363fc6b0
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
It looks like a bunch of files have also changed content not just the namespace :/

**Comment by jcrombez** [comment]
Oh ? maybe my Visual Studio isn't rightly configured and reformated some stuff the wrong way ? Or do you see actual code modification ?

**Comment by thestonefox** [comment]
I'm not sure, i think it's best if i download the code and look over it, github isn't being helpful showing the modifications.

**Comment by thestonefox** [comment]
I did a big ass PR that name spaces the lot, so it supersedes this

https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/540

**Pull request closed without merging**
