### PR TITLE
feat(Interaction):support for Steam Rig Prefab

### PR DESCRIPTION
**Pull request by vad710**
This allows the code to work with both the original Steam prefab and the prefab included with the code.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6ce4413d6e5f6b147de2946cdfa75765cb8e3c6f
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
The one reason I can think for why Valve have the other CameraRig prefab is because if you look at their test throw example scene, you can specify a rigidbody attachpoint within the editor.

These rigidbodies exist within the editor in the test throw example scene, meaning they're able to be dragged and dropped to set the attach point.

If you're using the standard CameraRig (not the one from the test throw scene). Then they have no attachpoints you can specify.

Is this correct? Or is the standard CameraRig the one that is broken?

Why oh why do Valve have 2 camera rigs?! :(

**Comment by 10FingerArmy** [comment]
How I understand it one can freely exchange controller models at any point in time. Having this in mind it is actually mandatory to prepare for that and dynamically find the attach points instead of using them from the initial setup which is only valid for one controller. Or are the attachments the same for every controller?

**Comment by thestonefox** [comment]
I'm not sure how their controller models work. They seem to only support their official vive models which seem to be streamed in via the library. They are supposed to have examples that shows how other models are supported but they don't seem to work.

I'd love to understand this to improve the current situation, because it sucks not being able to use the default the camera rig.

**Comment by vad710** [comment]
They published a plugin for the Hydra and I believe it has the Hydra models - but I do not have a hydra to test. I saw on reddit the other day that there is a leap motion plugin, but not sure how they deal with the model. I have been pushing the folks at Ximmerse to produce a plugin - if they do, this is something I could test as I have their hardware.

**Comment by thestonefox** [comment]
@vad710 that would be good if you could test on another hardware model.

Really want to get to the bottom of this CameraRig issue. Valve are tight lipped on it :(

**Comment by vad710** [comment]
Did GitCop reject the commit because I missed the space between the ":" and the message?

**Comment by thestonefox** [comment]
@vad710 yeah I think so

**Comment by thestonefox** [comment]
This is superseded by PR https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/233

**Pull request closed without merging**
