### PR TITLE
feat(Interaction): improve grabbable detection

### PR DESCRIPTION
**Pull request by 10FingerArmy**
This is a first independent part of a bigger change to support rigidbody based buttons. So far when enabling the rigidbody feature of the InteractGrab script it was checking for interactable objects. This is too broad. It should only check for grabbable objects. Also the rigidbody on the controller should freeze all constraints to eliminate strange side effects due to a spinning collider.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bb44c8eb3247ffce8dfd3e4ff2c7ee7a2fc1a79c
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
Hi, thanks for taking time to make a PR.

The issue is though you now have grab related code inside the touch code.

The InteractTouch should not know about the concept of grabbing.

The IsValidGrab check is checking to see if the object is interactable because without that first check there is never a touchable object and you cannot grab an object that cannot be touched.

Perhaps the wording of IsValidGrab is too ambiguous, but it basically means Is this item something I can grab because it's touchable.

Also, freezing rigidbody rotations/positions causes havoc with the physics engine if you're holding objects using fixed joints, I wouldn't recommend this practice or you get some crazy physics where items fly off to never be seen again!

**Comment by 10FingerArmy** [comment]
Misunderstanding with the freezing I think. You can easily see the wrong behaviour when selecting the controller in the hierarchy. Then the sphere collider will be shown. Now gently touch another rigidbody so that it moves a bit. All of a sudden the sphere collider on the controller starts to rotate. Now you get all kinds of weird effects. Must not happen.

**Comment by thestonefox** [comment]
@10FingerArmy Ah you're talking about the invisible rigidbody that gets created to mimic having the controllers push items around, yeah?

If you freeze it's position and rotation does it still track the controller correctly? If so then I don't see an issue with freezing that because it's just invisible anyway.

**Comment by 10FingerArmy** [comment]
I reduced the change to the freeze fix only for now until I have some more time to incorporate your other hints

**Comment by thestonefox** [comment]
Cool, I'll give it the once over in the morning and if everything is good I'll merge it 👍

**Comment by thestonefox** [comment]
I redid the rigidbody code and included this change in the rework (this wont merge now, but it's also redundant because of the other commit).

Commit for reference: 2da56bd91c0b54a4122169867988128816c758f3

**Pull request closed without merging**
