### PR TITLE
fix(Headset): show warning if fade script is not present

### PR DESCRIPTION
**Pull request by Frostlock**
Did requested clean up.
Tried to amend my latest commit message to comply with gitcop, not sure if I can do anything about older commit messages though.

BTW: You made me use vi! Ack! :) 
Luckily google is my friend, "esc :wq" for the win.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1a4983b1da3d4607a2aaa2b8f58d01ea840bd09e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: c2e8f0b1fa63a6fa2cb240f0ba5a009ff7517eac
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by Frostlock** [comment]
Yes GitCop, I'll try to do better next time!

**Comment by thestonefox** [comment]
Heh, you've got some rebasing to do. You're trying to commit a bunch of things, where you really only want to commit hash: d2593ca

**Comment by Frostlock** [comment]
You mean I have 4 commits in there and you would only like to see one for such a small change?
I have always understood that cleaning up old commits / rewriting history is not really recommended.
Not sure I understand correctly what you would like me to do here.

Pointers are welcome :)

**Comment by thestonefox** [comment]
rewriting history is one of the awesome things about git :)

That's the great thing about pull requests.

You have a master branch (that is your history of your product, and this is the true record of history, which you don't want to alter, it's like your audit log).

But on your local branch that you are wanting to pull request, you want that as neat as possible so not showing mistakes before it gets into the master branch.

Your local branch is your sandbox where you get the opportunity to get things right before it goes into the master audit log.

Obviously if something sneaks into the master branch (like a bug) then you don't rebase that out, you do another fix and show that as a new commit.

separate branches like this is one of the things that makes git a really cool solution over others like svn for example.


So in your case, what you would want to do, is do a git rebase, delete the other commits that aren't relevent and just have your local branch commit history nice and neat. Then push that up to master.

Does that make sense? seems like i've written a wall of text! :p

**Comment by Frostlock** [comment]
Good point on seeing those local branches as sandboxes. That will also make me more comfortable when messing around :)
I'll set to cleaning that up and a third pull request attempt will follow.
I'm enjoying git a lot but still have a lot to learn on proper usage.

**Pull request closed without merging**
