### PR TITLE
feat(Climbing): climb release can height adjust or physics fall

### PR DESCRIPTION
**Pull request by mattboy64**
Instead of assuming a physics based fall is required, the climbing
object now checks if we at or below ground level. If it is, it will
allow the VRTK_HeightAdjustTeleport object to move you up rather
than assuming you must enter a physics falling state.

The ground plane of example 37 (ClimbingFalling) now uses a box
collider on the ground. This should remove the falling through the
floor bug that was reported.

### CODE REVIEW

**Comment by mattboy64** [comment]
This should fix #453

**Comment by mattboy64** [comment]
@thestonefox let me know when you have a change to take a look at this. It should fix most problems with climbing onto ledges as well as falling through the world.

**Comment by thestonefox** [comment]
Just lowercase the commit subject line so it should be:

`feat(Climbing): climb release can height adjust or physics fall`

Then looks good to merge

**Comment by mattboy64** [comment]
Done. Thanks fox

**Pull request merged**
