### PR TITLE
fix(Headset): show warning if fade script is not present

### PR DESCRIPTION
**Pull request by Frostlock**

### CODE REVIEW

**Comment by Frostlock** [comment]
Third time is a charm? :)
Turns out this was more about me learning git than adding a lot of value to the toolkit but hey all in the name of science ;-)

**Comment by thestonefox** [comment]
All looks good!, I'll merge in a bit, just finishing off some stuff on the bow mechanics, so i'll merge your stuff and rebase into mine :)

**Comment by thestonefox** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart:

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 698556c037a3fb5789b5efac67f2f71ba274865c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
Make a separate branch for your other commit, you don't want it to come in with this pull request,

**Comment by Frostlock** [comment]
O dear, I din't realize additional commits on my master branch would automatically be added to this pull request. I have cleaned it out again.

**Comment by thestonefox** [comment]
@Frostlock You're officially the second contributor to this repo! :cake:

**Comment by Frostlock** [comment]
And also the smallest :)
Thanks for all the git coaching!

**Comment by thestonefox** [comment]
no worries, git is a beast to master!

**Pull request merged**
