### PR TITLE
Feat/object highlighting

### PR DESCRIPTION
**Pull request by thestonefox**

### CODE REVIEW

**Comment by SmartCarrion** [comment]
I can't wait to try this one!  i've been struggling with different methods to do this and nothing was working.

**Comment by thestonefox** [comment]
@SmartCarrion download the branch and see how it works for you:

https://github.com/thestonefox/SteamVR_Unity_Toolkit/archive/feat/object-highlighting.zip

There aren't any instructions yet in the docs though. Basically what you need to do on your Interactable Object is also attach the `VRTK_SolidMaterialSwapHighlighter` component and that will use a custom highlighter to swap out the materials rather than change the material colours.

**Comment by thestonefox** [comment]
FYI the `VRTK_SolidMaterialSwapHighlighter ` does break batching.

**Comment by thestonefox** [comment]
FYI: `VRTK_SolidMaterialSwapHighlighter` no longer breaks batching :)

**Comment by thestonefox** [comment]
Superseded with https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/574

**Pull request closed without merging**
