### PR TITLE
feat(Editor): add interactable custom inspector

### PR DESCRIPTION
**Pull request by Blueteak**
Adds a custom inspector for VRTK_InteractableObject which provides a more readable and collapsable interface within the Editor.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6fddbb65e3b493ce53581ec88da7284e0e47ab60
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 705442e94c001b46b6936f5f9eaac5837c28122c
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
Just had a play, there's a really annoying problem with custom inspectors...

They don't inherit down to their inherited classes, and if you set the bool flag to true to make it inherit then in your inherited class you don't see any local public variables.

This means either developers have to get used to 1 inspector panel for interactable objects, but whenever they extend it then they have to use the old (not custom) inspector panel, which i think will be really confusing for people. Alternatively, every time you inherit it, you'll have to build a custom inspector, which again is a complete ballache.

As I don't really know anything about custom inspectors, this may be something that's been resolved in unity, so if anyone knows a better way to do this (without suggesting sub classes because that will be a breaking change and will have to wait for 3.0 release!)

**Comment by thestonefox** [comment]
What about this for the top level layout:

image

So not bother having the labels for `Touch` `Grab` Use` - and then having the Foldout titles in bold instead (to draw attention to them)

changing the foldout font style seems a bit long winded, this is how i saw how to do it:

```
GUIStyle guiStyle = EditorStyles.foldout;
FontStyle previousStyle = guiStyle.fontStyle;
guiStyle.fontStyle = FontStyle.Bold;
viewTouch = EditorGUILayout.Foldout(viewTouch, "Touch Options", guiStyle);
guiStyle.fontStyle = previousStyle;
```

**Comment by thestonefox** [comment]
Is it possible to get the `Strength` and `Duration` on the same line as `Rumble On Touch` ?

image

**Comment by thestonefox** [comment]
image

image


Track/Rotator Objects uses `Detach Threshold` it's the distance the controller has to be away from the object for it to force letting go (rather than using a force)

**Comment by xEvoGx** [comment]
I approve this message!

**Comment by 10FingerArmy** [comment]
I suggest to hide the foldouts if not needed, eg don't show grab options if it is not grabbable

**Comment by thestonefox** [comment]
Superseded by https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/470

**Pull request closed without merging**
