### PR TITLE
feat(Climbing): Added Climbing Stamina

### PR DESCRIPTION
**Pull request by sidcitris**
Add climbing stamina class that extends the existing VRTK_PlayerClimb
class. The VRTK_PlayerClimbStamina script is added to the CameraRig in
of place the previous climbing script.

The players min reach and max reach can be set where the distance in
the xz plane between the controller and the head determine the effect
on stamina. A distance less than min reach will not decrease stamina
while a distance beyone max reach will apply the maximum damge to
stamina.

The player can regenerate stamina when either no hands are holding a
climbable object, or when both hands are holding climbable objects.
The VRTK currently doesn't support grabbing one object with both hands
but should work when it is implemented.

Example 039_CameraRig_ClimbingStamina has been added to demonstrate
the climbing stamina as well as a useful grip stamina visualization
prefab which has been added.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e45d528bb8244e81f2f7270e996e34f3fbcd530
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by sidcitris** [comment]
This is my first attempt at a pull request on GitHub. Please let me know what if I messed anything up or need to change anything. This attempts to address issue #397 . The only issue I had was it is currently impossible to grab the same object with both controllers. This prevents stamina regeneration when holding climbable objects with both controllers. I also added the example is example 39 as I believe there are at least one open pull request using example 38 and I didn't want to conflict with them. The other issue I had was when a second controller grabs, the first controller grab is no longer active. To work around this, I store the secondary hold location of the first controller, and only keep it as an active hold while the first controller hasn't moved more than a small amount from its original position.  Any feedback is welcome.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 3b57dd579d57d912537bc5a203292799e25d1a60
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by xEvoGx** [comment]
Awesome! Can't wait to check this out

**Comment by xEvoGx** [comment]
Is there a way for us to check this out? Stone said I could grab PR files but I'm not seeing it.

**Comment by thestonefox** [comment]
You just need to go to the fork/branch that the PR was created from and download the zip file (or git clone it)

https://github.com/sidcitris/SteamVR_Unity_Toolkit/archive/feat/climb-staminia.zip

**Comment by xEvoGx** [comment]
Right but how did you get there from the main page? I looked in Branches, and I only see three which are all yours. I his commits on his PR, including the 11 files he changed, but I'm either blind or stupid as I don't see where to pull down the zip. 

Sorry I'm new to Git! :smile:

**Comment by sidcitris** [comment]
If you go to my repo here:
https://github.com/sidcitris/SteamVR_Unity_Toolkit
You can change branch on the left to feat/climb-stamina, and then click the green "Clone or download" button, and click zip to get to the link stone posted.

**Comment by xEvoGx** [comment]
Got it! I can click on the number next to Fork, pull up that map and then find your name and THEN see your code, phew! 

I appreciate it sid!

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e45d528bb8244e81f2f7270e996e34f3fbcd530
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 0e45d528bb8244e81f2f7270e996e34f3fbcd530
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by sidcitris** [comment]
I tried to merge the latest code and messed something up. I am going to try a clean pull request.

**Pull request closed without merging**
