### PR TITLE
feat(Interaction): Add highlight on touch

### PR DESCRIPTION
**Pull request by Mishkun**
VRTK_HighlightOnInteract adds outline to VRTK_InteractableObject's that changes its colour on touch. That outline done IKEA VR App style. It also can show/hide associated tooltip on touch.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b323b4f0b0c26925417d64e3c04570e0cde4f33a
  * Your commit message body contains a line that is longer than 72 characters
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b323b4f0b0c26925417d64e3c04570e0cde4f33a
  * Your commit message body contains a line that is longer than 72 characters
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by thestonefox** [comment]
You'll need to squash these commits into one and ensure the commit message meets the contributing guidelines.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b323b4f0b0c26925417d64e3c04570e0cde4f33a
  * Your commit message body contains a line that is longer than 72 characters
  * Your subject line is longer than 72 characters

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: b323b4f0b0c26925417d64e3c04570e0cde4f33a
  * Your commit message body contains a line that is longer than 72 characters
  * Your subject line is longer than 72 characters

 * Commit: 441931b18fc74fb810b31d5a8c96b142b8da5536
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: e86b9dba6e161e786bd06fb3c263ce369a0a4109
  * Your commit message body contains a line that is longer than 72 characters
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

 * Commit: bb534ca1e80a823feec01865a25f4e6439d94ac4
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Pull request closed without merging**
