### PR TITLE
Update from original

### PR DESCRIPTION
**Pull request by Frostlock**
Trying to update my fork, two commits below are just a comment and an uncomment, no change

### CODE REVIEW

**Comment by thestonefox** [comment]
Can I close this pull request without merge then ?

**Comment by Frostlock** [comment]
Sure, I'm just trying to figure out how to update my own fork with your latest commits.
I don't use github often enough, always need to figure it out again :)

**Comment by thestonefox** [comment]
Do you have my branch set up as your remote upstream?

if so, then you just need to git fetch that upstream then git rebase upstream master

(if that doesn't make sense, let me know I'll help out more)

**Comment by Frostlock** [comment]
I tried using the github documentation. But I just did a merge instead of a rebase.
I think my fork is up to date again but I have the feeling all your updates have now been rolled up into a commit on my branch.
Come to think of it, this might be why you said rebase :)

**Comment by Frostlock** [comment]
Ah I found a way out, I reset my branch to your latest version. Worked like a charm. :)
FYI
http://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream

Sorry for the hassle :)

**Pull request closed without merging**
