### PR TITLE
feat(Simple Pointer) add hit normal to marker and related class

### PR DESCRIPTION
**Pull request by WildStyle69**
Sometime its useful to get the hit normal / surface direction from
the DestinationMarkerEventArgs, for instance in drawing applications
or when you want to orient objects to align with the pointer hit
surface.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: bb00d78402c336d9ef9bdf373e260f2cabed1b5e
  * Commits must be in the following format: **%{type}(%{scope}): %{description}**

Guidelines are available at https://github.com/thestonefox/SteamVR_Unity_Toolkit

---
This message was auto-generated by https://gitcop.com

**Comment by WildStyle69** [comment]
Also would be nice to make some of the private variables in VRTK_SimplePointer protected?

`private GameObject pointerHolder;`
`private GameObject pointer; `
`private GameObject pointerTip;`
`private Vector3 pointerTipScale = new Vector3(0.05f, 0.05f, 0.05f);`

**Comment by getwilde** [comment]
I recently needed to know the child collider that was being hit (and didn't want to add a kinematic rigidbody to that child).  This information was available to me in RaycastHit.collider.  Would it be worth returning the RaycastHit in DestinationMarkerEventArgs?

**Comment by WildStyle69** [comment]
@getwilde -- right, I did think returning the RaycastHit might be more universally useful, however that would be a more fundamental change. I'm interested to hear @thestonefox thoughts on the topic.

**Comment by WildStyle69** [comment]
This pull request no longer required... its been taken care of by another.
https://github.com/thestonefox/SteamVR_Unity_Toolkit/pull/592

**Comment by getwilde** [comment]
Thanks for the heads up on #592

**Pull request closed without merging**
