### PR TITLE
feat(RoomExtender): adds toggle, gizmo and controller example #189

### PR DESCRIPTION
**Pull request by appdevtk**
I have added the ability to toggle the script, control it
with the controllers and extended the example scene
to showcase the new usage.
See VRTK_RoomExtender_ControllerExample.cs

I also added a Gizmo to show the extended playArea,
see example (028)

See #189 for more information.

### CODE REVIEW

**Comment by thestonefox** [comment]
I think i know the issue now with start up. If you have the "Press to enable" flag on the controller example then the play area only moves when you press the button... But when the scene first loads, even if you're not pressing the enable button it still adjusts your position by default, which causes your play area to wizz out to the extents of the extended boundaries.

I would expect it to leave the play area in the original starting position unless i'm pressing the button to move around.

Would you expect this to be solved by the user just unchecking the "additional movement enabled" checkbox on the RoomExtender script? (As this does solve the problem).

Also, I'd use TouchpadPress instead of TouchpadTouch. just brushing my finger on the touchpad obviously triggers it, which can move my play area when I wasn't intending to do it.


Finally, I also don't seem to be able to move to the extents of the extended boundary (as visualised with the red gizmo border in the editor). It seems to show my limits as being probably twice as large as I can actually reach: settings are:

image


And the gizmo shows:

image

I can probably walk from the hinged box (and weird character joint thing) to about the far edge of my blue play area boundary, but I cannot reach the drawer that is on the other extended boundary.

**Comment by thestonefox** [comment]
Just tested it again, all seems to be working as I expected now.

Anything else you want to do on it before merge?

**Comment by appdevtk** [comment]
I've updated the Readme and removed the linearTransform movement. I think it's ready to go.

**Comment by couba** [comment]
Great work with RoomExtender. This is probably easy but I can't figure it out. In my program I move my CameraRig to fixed locations. Now I'd like to use your script, but everytime I teleport the position of the extended room space is in different position depending on where I actually stand in the real room. What I need is that the extended room is centered at my destination. I think if I had a vector between center of the CameraRig and the extended room, it would do the job, but I don't know how to get it. Any  tips? Thanks

**Comment by appdevtk** [comment]
There is a vector that keeps track of the CameraRig movement:
[HideInInspector]
	public Vector3 relativeMovementOfCameraRig = new Vector3();

This is used to render the gizmo in the correct place. You could look at the VRTK_RoomExtender_PlayAreaGizmo script.

Lets say you teleport to point X. I think you can teleport to 
X - vrtk_RoomExtender.relativeMovementOfCameraRig to get the correct position.

I hope this helps.

**Comment by couba** [comment]
Thats exactly what I needed. But there should be a + in the equation. Thanks a lot

**Pull request merged**
